(New) SRS SAR Wind - create new handler - creating plot on the fly
aodn/python-aodndata pull request #288
Opened 2021-11-04 03:18 UTC by lbesnard

2021-11-04 03:27 UTC, lbesnard commented
@DelphiWard FYI. a new handler which creates a plot on the fly to be attached to the NetCDF.
@leonardolaiolo FYI

No need to merge it yet

2022-05-17 06:46 UTC, lbesnard commented
The last two commits remove the dependence to Cartopy and the creation of on-the-fly plots

2022-07-12 04:56 UTC, lbesnard commented
https://github.com/aodn/backlog/issues/4197

2022-07-14 06:45 UTC, lbesnard commented
The last commits re-revert the changes to re-add cartopy and the creation of plots. it might happen

2022-08-09 23:51 UTC, digorgonzola requested changes

2022-08-09 23:51 UTC, digorgonzola commented on .github/workflows/test.yml
> +    - name: cartopy - build Gtest needed for proj build
I think we should use a binary if possible for this so the actions don't take ages

2022-08-10 01:21 UTC, merged