(Feat) add fishsoop dest_path
aodn/python-aodndata pull request #386
Opened 2024-05-20 06:19 UTC by lbesnard

2024-05-20 06:20 UTC, lbesnard commented
To be merged once everything is confirmed by facility

2024-05-28 00:25 UTC, bpasquer requested changes

2024-05-28 00:25 UTC, bpasquer commented on aodndata/soop/soop_fishsoop.py
> +                              (?P<nc_time_cov_start>[0-9]{8}T[0-9]{6}Z)_
The data code should be TP

2024-05-28 00:25 UTC, bpasquer commented on test_aodndata/soop/test_fishsoop.py
> +        good_nc_nrt = os.path.join(TEST_ROOT, 'IMOS_SOOP-FishSOOP_T_20240310T094642Z_FV00_786.nc')
see comment above

2024-05-28 00:25 UTC, bpasquer commented on test_aodndata/soop/test_fishsoop.py
> +        self.assertEqual(dest_path_soop_fishsoop(good_nc_dm),
same as above

2024-05-28 00:32 UTC, bpasquer commented on test_aodndata/soop/test_fishsoop.py
> +                         'IMOS/SOOP/SOOP-FishSoop/REALTIME/2024/03/{basename}'.format(
FishSOOP

2024-05-28 00:32 UTC, bpasquer commented on aodndata/soop/soop_fishsoop.py
> +        return os.path.join('IMOS', 'SOOP', 'SOOP-FishSoop', data_mode,
FishSOOP

2024-05-28 00:33 UTC, bpasquer commented on test_aodndata/soop/test_fishsoop.py
> +                         'IMOS/SOOP/SOOP-FishSoop/REALTIME/2024/03/{basename}'.format(
more SOOP

2024-05-28 00:43 UTC, bpasquer commented on test_aodndata/soop/test_fishsoop.py
> +        good_nc_nrt = os.path.join(TEST_ROOT, 'IMOS_SOOP-FishSOOP_PT_20240310T094642Z_FV00_786.nc')
TP instead of PT

2024-05-28 01:23 UTC, merged